import type { DiagramNode } from '@engine/narrative/architecture/types'

/** The trunk, the sampler and the heads — everything downstream of the embedder. */
export const trunkNodes: DiagramNode[] = [
  {
    id: 'template-module',
    shape: 'box',
    x: 464,
    y: 52,
    width: 96,
    height: 36,
    label: 'Template module',
    sub: '(2 blocks)',
    stage: 'templates',
  },
  {
    id: 'msa-module',
    shape: 'box',
    x: 580,
    y: 52,
    width: 88,
    height: 36,
    label: 'MSA module',
    sub: '(4 blocks)',
    stage: 'msa',
  },
  {
    id: 'pairformer',
    shape: 'box',
    x: 688,
    y: 46,
    width: 140,
    height: 52,
    label: 'Pairformer',
    sub: '(48 blocks)',
    stage: 'pairformer',
  },

  // --- diffusion -----------------------------------------------------------
  {
    id: 'noise',
    shape: 'chip',
    x: 888,
    y: 62,
    width: 44,
    height: 15,
    label: 'noise',
    stage: 'sample',
    note: 'σ₀ · 𝒩(0, I) — a cloud with radius of gyration ≈ 2240 Å.',
  },
  {
    id: 'noise-sum',
    shape: 'junction',
    x: 944,
    y: 62,
    width: 16,
    height: 16,
    note: 'Churn: a little noise added back before each Heun step.',
  },
  {
    id: 'diffusion-module',
    shape: 'box',
    x: 978,
    y: 46,
    width: 132,
    height: 52,
    label: 'Diffusion module',
    sub: '(3 + 24 + 3 blocks)',
    stage: 'denoise',
  },
  {
    id: 'structure',
    shape: 'chip',
    x: 1136,
    y: 62,
    width: 52,
    height: 15,
    label: 'structure',
    stage: 'sample',
    note: 'sampled_atom_pos — b 1354 3, after 32 steps and 63 denoiser calls.',
  },

  // --- confidence ----------------------------------------------------------
  {
    id: 'confidence-module',
    shape: 'box',
    x: 1290,
    y: 12,
    width: 116,
    height: 48,
    label: 'Confidence module',
    sub: '(4 blocks)',
    stage: 'confidence',
  },
  {
    id: 'plddt-scale',
    shape: 'swatch',
    x: 1290,
    y: 66,
    width: 82,
    height: 6,
    // The pLDDT ramp everyone reads AlphaFold output with: low is orange.
    swatch: ['#f0724a', '#f2c14a', '#6fd3c8', '#2f6bd8'],
    stage: 'confidence',
    note: 'pLDDT, 50 bins over 0–100, predicted per atom.',
  },
]
