import type { GraphEdge, GraphNode } from '../types'
import { port, portId } from './port'

const G = 'diffusion_module'
const p = (name: string, side: 'in' | 'out') => portId(G, name, side)

/** Inside `DiffusionModule` — Algorithm 20. An hourglass: atoms, tokens, atoms. */
export const denoiserNodes: GraphNode[] = [
  port(G, 'noised_atom_pos', 'b m 3', 'in', [1, 1354, 3]),
  port(G, 'times', 'b', 'in', [1]),
  port(G, 'single_trunk_repr', 'b n dst', 'in', [1, 199, 384]),
  port(G, 'single_inputs_repr', 'b n dsi', 'in', [1, 199, 417]),
  port(G, 'pairwise_trunk', 'b n n dpt', 'in', [1, 199, 199, 128]),
  {
    id: 'single_conditioning',
    label: 'Single conditioning',
    module: 'SingleConditioning',
    kind: 'op',
    group: G,
    algorithm: 'Algorithm 21',
    sourceSymbol: 'SingleConditioning.forward',
    traceId: 'single_conditioning',
    summary: 'Trunk single ⊕ raw inputs = 801, plus a Fourier embedding of ln σ.',
    detail: [
      'The 384-channel trunk output concatenated with the 417-channel raw inputs makes the skip connection around the trunk explicit.',
      'σ is passed through a random Fourier feature embedding of ¼ ln σ and added, so the denoiser always knows how far from the data manifold it is. Without that it could not choose between sketching the fold and nudging a side chain.',
    ],
  },
  {
    id: 'pairwise_conditioning',
    label: 'Pairwise conditioning',
    module: 'PairwiseConditioning',
    kind: 'op',
    group: G,
    algorithm: 'Algorithm 22',
    sourceSymbol: 'PairwiseConditioning.forward',
    traceId: 'pairwise_conditioning',
    summary: 'Trunk pair map ⊕ relative positions, through two transitions.',
    detail: [
      'The denoiser gets its own copy of the pair map. This is what supplies the attention bias inside the token transformer.',
    ],
  },
  {
    id: 'atom_pos_to_atom_feat',
    label: 'Embed coordinates',
    module: 'Linear',
    kind: 'op',
    group: G,
    summary: '3 → 128 channels per atom, added to the input embedder’s atom features.',
  },
  {
    id: 'atom_encoder',
    label: 'Atom encoder',
    module: 'DiffusionTransformer',
    kind: 'op',
    group: G,
    algorithm: 'Algorithm 5',
    sourceSymbol: 'DiffusionTransformer.forward',
    traceId: 'atom_encoder',
    repeats: '×3 blocks',
    summary: 'Windowed attention over 1354 atoms, 27 per window.',
    detail: [
      'Local chemistry is resolved here so the token transformer can concentrate on the fold.',
    ],
  },
  {
    id: 'atom_to_token_pool_diff',
    label: 'Pool atoms → tokens',
    module: 'AtomToTokenPooler',
    kind: 'op',
    group: G,
    sourceSymbol: 'AtomToTokenPooler.forward',
    traceId: 'atom_to_token_pool',
    summary: 'The waist of the hourglass: 1354 × 128 → 199 × 768.',
    detail: [
      'This is why the diffusion module is affordable. Global attention costs 199² = 39,601 pairs instead of 1354² = 1.83 M.',
    ],
  },
  {
    id: 'token_transformer',
    label: 'Token transformer',
    module: 'DiffusionTransformer',
    kind: 'op',
    group: G,
    algorithm: 'Algorithm 23',
    sourceSymbol: 'DiffusionTransformer.forward',
    traceId: 'token_transformer',
    repeats: '×24 blocks',
    summary: 'Full attention over 199 tokens at 768 channels. The fold is decided here.',
    detail: [
      'Adaptive LayerNorm is how σ steers the computation: the scale and shift of every normalisation are predicted from the conditioning vector, and every residual branch is gated by a zero-initialised term. At initialisation each block is an identity map, and training opens them gradually.',
    ],
  },
  {
    id: 'broadcast_to_atoms',
    label: 'Broadcast to atoms',
    module: 'Linear + repeat',
    kind: 'op',
    group: G,
    summary: 'Each token’s 768-vector is copied to every atom it owns.',
    detail: [
      'Added back to the encoder’s atom features — a skip connection across the hourglass.',
    ],
  },
  {
    id: 'atom_decoder',
    label: 'Atom decoder',
    module: 'DiffusionTransformer',
    kind: 'op',
    group: G,
    algorithm: 'Algorithm 6',
    sourceSymbol: 'DiffusionTransformer.forward',
    traceId: 'atom_decoder',
    repeats: '×3 blocks',
    summary: 'Three more windowed blocks, refining locally.',
  },
  {
    id: 'atom_feat_to_atom_pos_update',
    label: 'Predict update',
    module: 'LayerNorm + Linear',
    kind: 'op',
    group: G,
    summary: '128 → 3: one displacement per atom.',
  },
  port(G, 'atom_pos_update', 'b m 3', 'out', [1, 1354, 3]),
]

export const denoiserEdges: GraphEdge[] = [
  { from: p('times', 'in'), to: 'single_conditioning', tensor: 'times', symbolic: 'b' },
  { from: p('single_trunk_repr', 'in'), to: 'single_conditioning', tensor: 'single_trunk_repr', symbolic: 'b n dst' },
  { from: p('single_inputs_repr', 'in'), to: 'single_conditioning', tensor: 'single_inputs_repr', symbolic: 'b n dsi' },
  { from: p('pairwise_trunk', 'in'), to: 'pairwise_conditioning', tensor: 'pairwise_trunk', symbolic: 'b n n dpt' },
  { from: p('noised_atom_pos', 'in'), to: 'atom_pos_to_atom_feat', tensor: 'noised_atom_pos', symbolic: 'b m 3' },
  { from: 'atom_pos_to_atom_feat', to: 'atom_encoder', tensor: 'noised_repr', symbolic: 'b m da', concrete: [1, 1354, 128] },
  { from: 'single_conditioning', to: 'atom_encoder', tensor: 'single_cond', symbolic: 'b n (dst+dsi)', concrete: [1, 199, 801] },
  { from: 'atom_encoder', to: 'atom_to_token_pool_diff', tensor: 'atom_feats', symbolic: 'b m da', concrete: [1, 1354, 128] },
  { from: 'atom_to_token_pool_diff', to: 'token_transformer', tensor: 'tokens', symbolic: 'b n dtok', concrete: [1, 199, 768] },
  { from: 'single_conditioning', to: 'token_transformer', tensor: 'single_cond', symbolic: 'b n (dst+dsi)', concrete: [1, 199, 801] },
  { from: 'pairwise_conditioning', to: 'token_transformer', tensor: 'pairwise_cond', symbolic: 'b n n dp', concrete: [1, 199, 199, 128] },
  { from: 'token_transformer', to: 'broadcast_to_atoms', tensor: 'tokens', symbolic: 'b n dtok', concrete: [1, 199, 768] },
  { from: 'atom_encoder', to: 'broadcast_to_atoms', tensor: 'atom_feats (skip)', symbolic: 'b m da', concrete: [1, 1354, 128] },
  { from: 'broadcast_to_atoms', to: 'atom_decoder', tensor: 'atom_feats', symbolic: 'b m da', concrete: [1, 1354, 128] },
  { from: 'atom_decoder', to: 'atom_feat_to_atom_pos_update', tensor: 'atom_feats', symbolic: 'b m da', concrete: [1, 1354, 128] },
  { from: 'atom_feat_to_atom_pos_update', to: p('atom_pos_update', 'out'), tensor: 'atom_pos_update', symbolic: 'b m 3' },
]
