import type { Step } from '../types'

/** The atom half of the hourglass, and the sampling loop that drives it. */
export const diffusionAtomSteps: Step[] = [
  {
    id: 'atom_encoder',
    stage: 'diffusion',
    title: 'Encode the noisy atoms',
    module: 'DiffusionTransformer',
    algorithm: 'Algorithm 5',
    sourceSymbol: 'DiffusionTransformer.forward',
    traceId: 'atom_encoder',
    repeats: '×3 blocks',
    summary: 'Noisy coordinates are projected to 128 channels and attended over within windows.',
    detail: [
      'The current noisy coordinates are turned into per-atom features by a linear map from 3 channels to 128, added to the atom features from the input embedder and to a broadcast of the token-level conditioning.',
      'Three blocks of windowed attention follow — 27 atoms per window, the same local pattern as the input embedder. Local chemistry is resolved here so the token transformer can concentrate on the fold.',
    ],
    inputs: [
      { name: 'noised_repr', symbolic: 'b m da', concrete: [1, 1354, 128] },
      { name: 'pairwise_repr', symbolic: 'b nw w (w*2) dap', concrete: [1, 51, 27, 54, 16] },
    ],
    outputs: [{ name: 'atom_feats', symbolic: 'b m da', concrete: [1, 1354, 128] }],
  },
  {
    id: 'atom_to_token_pool',
    stage: 'diffusion',
    title: 'Pool atoms up to tokens',
    module: 'AtomToTokenPooler',
    sourceSymbol: 'AtomToTokenPooler.forward',
    traceId: 'atom_to_token_pool',
    summary: 'Mean over the atoms each token owns: 1354 × 128 → 199 × 768.',
    detail: [
      'A ReLU-projected mean pool, segmented by `molecule_atom_lens`. A glycine token averages 4 atoms, a tryptophan 14, a ligand-atom token exactly 1.',
      'This is the waist of the hourglass, and the reason the diffusion module is affordable: global attention costs 199² = 39,601 pairs instead of 1354² = 1.83 M.',
    ],
    math: [{ tex: 't_i = \\frac{1}{|A_i|}\\sum_{a \\in A_i} \\mathrm{ReLU}(W a), \\qquad \\sum_i |A_i| = m = 1354' }],
    inputs: [{ name: 'atom_feats', symbolic: 'b m da', concrete: [1, 1354, 128] }],
    outputs: [{ name: 'tokens', symbolic: 'b n dtok', concrete: [1, 199, 768] }],
  },
  {
    id: 'token_transformer',
    stage: 'diffusion',
    title: 'Reason globally over tokens',
    module: 'DiffusionTransformer',
    algorithm: 'Algorithm 23',
    sourceSymbol: 'DiffusionTransformer.forward',
    traceId: 'token_transformer',
    repeats: '×24 blocks',
    summary: 'Full attention over 199 tokens at 768 channels, biased by the conditioned pair map.',
    detail: [
      'Twenty-four blocks of full attention-pair-bias, conditioned on the noise level through adaptive layer norm. This is where the global fold is decided.',
      'Adaptive LayerNorm is how σ steers the computation: the scale and shift of every normalisation are predicted from the conditioning vector, and the output of every residual branch is gated by a zero-initialised term. At initialisation each block is an identity map, and training opens them gradually.',
    ],
    math: [{ tex: '\\mathrm{AdaLN}(x, c) = \\left(1 + \\gamma(c)\\right) \\odot \\frac{x - \\mu}{\\sigma_x} + \\beta(c)' }],
    inputs: [
      { name: 'noised_repr', symbolic: 'b n dtok', concrete: [1, 199, 768] },
      { name: 'pairwise_repr', symbolic: 'b n n dp', concrete: [1, 199, 199, 128] },
    ],
    outputs: [{ name: 'tokens', symbolic: 'b n dtok', concrete: [1, 199, 768] }],
  },
  {
    id: 'atom_decoder',
    stage: 'diffusion',
    title: 'Broadcast back to atoms and predict the update',
    module: 'DiffusionTransformer',
    algorithm: 'Algorithm 6',
    sourceSymbol: 'DiffusionTransformer.forward',
    traceId: 'atom_decoder',
    repeats: '×3 blocks',
    summary: 'Token features are broadcast to their atoms, refined locally, mapped to a 3-vector each.',
    detail: [
      'Each token\'s 768-vector is projected down and copied to every atom it owns, added back to the encoder\'s atom features — a skip connection across the hourglass. Three more windowed blocks refine locally.',
      'A final linear map takes 128 channels to 3, giving one displacement per atom. Multiply by c_out, add c_skip times the input, and that is the denoised structure.',
    ],
    inputs: [{ name: 'atom_feats', symbolic: 'b m da', concrete: [1, 1354, 128] }],
    outputs: [{ name: 'atom_pos_update', symbolic: 'b m 3', concrete: [1, 1354, 3] }],
  },
  {
    id: 'edm_sample',
    stage: 'diffusion',
    title: 'Walk the ladder down',
    module: 'ElucidatedAtomDiffusion.sample',
    algorithm: 'Algorithm 18',
    sourceSymbol: 'ElucidatedAtomDiffusion.sample',
    repeats: '×32 steps',
    summary: 'Stochastic churn, a Heun step, and a random rigid re-centring at every level.',
    detail: [
      'Each step: optionally add a little noise back (churn, with S_churn = 80), evaluate the denoiser, take an Euler step toward it, then evaluate again at the new point and average the two slopes — Heun\'s second-order correction. That is the 2× in 63 calls.',
      'Before every step the whole structure is randomly rotated and translated by `CentreRandomAugmentation`. The denoiser is not equivariant by construction, so equivariance is enforced by never letting it see a preferred frame.',
      'The measured trajectory is the clearest single number on this page: the radius of gyration falls from about 2240 Å at step 0 to 19.3 Å at step 32. A diffuse cloud of 1354 atoms collapses into something protein-sized.',
    ],
    math: [
      { tex: '\\hat{\\sigma} = \\sigma_i(1 + \\gamma), \\qquad \\hat{x} = x_i + \\sqrt{\\hat{\\sigma}^2 - \\sigma_i^2}\\;\\varepsilon,\\quad \\varepsilon \\sim \\mathcal{N}(0, S_{\\text{noise}}^2 I)' },
      { tex: 'd = \\frac{\\hat{x} - D_\\theta(\\hat{x}; \\hat{\\sigma})}{\\hat{\\sigma}}, \\qquad x_{i+1} = \\hat{x} + (\\sigma_{i+1} - \\hat{\\sigma})\\,\\tfrac{1}{2}\\left(d + d^{\\prime}\\right)' },
    ],
    inputs: [{ name: 'sigmas', symbolic: 'ts+1', concrete: [33] }],
    outputs: [{ name: 'sampled_atom_pos', symbolic: 'b m 3', concrete: [1, 1354, 3] }],
    defines: [
      {
        name: 'sampled_atom_pos',
        symbolic: 'b m 3',
        concrete: [1, 1354, 3],
        dtype: 'float32',
        description: 'The predicted structure: one Cartesian coordinate per heavy atom, in ångström.',
      },
    ],
  },
]
