import type { Step } from '../types'

/** The attentional half of the Pairformer block, and the finished trunk. */
export const pairformerAttentionSteps: Step[] = [
  {
    id: 'tri_attn_starting',
    stage: 'trunk',
    title: 'Triangle attention, around the starting node',
    module: 'TriangleAttention',
    algorithm: 'Algorithm 14',
    sourceSymbol: 'TriangleAttention.forward',
    traceId: 'tri_attn_starting',
    summary: 'Each row of the pair map attends within itself, biased by a second edge of the triangle.',
    detail: [
      'Row i of the pair map is treated as a sequence of 199 items, and attention runs along it. What makes it triangular is the bias: the logit for attending from j to k carries an additive term read off z_jk — the third edge of the triangle i–j–k.',
      'The implementation is neat about this. It packs the row index into the batch dimension, so a single attention call handles all 199 rows at once, and broadcasts the same n × n bias to every row.',
    ],
    math: [
      { tex: 'b^h_{jk} = W_b\\,\\mathrm{LN}(z_{jk})' },
      { tex: 'o_{ij} = \\sum_{k} \\mathrm{softmax}_k\\!\\left(\\frac{q_{ij}^{\\top} k_{ik}}{\\sqrt{c}} + b^h_{jk}\\right) v_{ik}' },
    ],
    inputs: [{ name: 'pairwise_repr', symbolic: 'b n n d', concrete: [1, 199, 199, 128] }],
    outputs: [{ name: 'out', symbolic: 'b n n d', concrete: [1, 199, 199, 128] }],
  },
  {
    id: 'tri_attn_ending',
    stage: 'trunk',
    title: 'Triangle attention, around the ending node',
    module: 'TriangleAttention',
    algorithm: 'Algorithm 15',
    sourceSymbol: 'TriangleAttention.forward',
    traceId: 'tri_attn_ending',
    summary: 'The same module with `node_type="ending"` — it transposes, attends, and transposes back.',
    detail: [
      'One flag separates this from the previous step. `need_transpose` swaps i and j on the way in and undoes it on the way out, so attention now runs down columns of the pair map rather than along rows.',
      'Four triangle operations, two multiplicative and two attentional, each covering a different orientation of the triangle: that is the complete pairwise update.',
    ],
    inputs: [{ name: 'pairwise_repr', symbolic: 'b n n d', concrete: [1, 199, 199, 128] }],
    outputs: [{ name: 'out', symbolic: 'b n n d', concrete: [1, 199, 199, 128] }],
  },
  {
    id: 'pairwise_transition',
    stage: 'trunk',
    title: 'Pairwise transition',
    module: 'Transition',
    algorithm: 'Algorithm 11',
    sourceSymbol: 'Transition.forward',
    traceId: 'pairwise_transition',
    summary: 'A SwiGLU feed-forward over all 39,601 pairs, 4× expansion.',
    detail: [
      'The per-pair non-linearity that closes the pairwise half of the block. 128 → 512 → 128, applied independently to every one of the 39,601 token pairs.',
    ],
    inputs: [{ name: 'x', symbolic: 'b n n d', concrete: [1, 199, 199, 128] }],
    outputs: [{ name: 'out', symbolic: 'b n n d', concrete: [1, 199, 199, 128] }],
  },
  {
    id: 'single_attention_pair_bias',
    stage: 'trunk',
    title: 'The single stream reads the pair map',
    module: 'AttentionPairBias',
    algorithm: 'Algorithm 24',
    sourceSymbol: 'AttentionPairBias.forward',
    traceId: 'single_attention_pair_bias',
    summary: 'Self-attention over 199 tokens, with the pair map added to every logit.',
    detail: [
      'The only place in the Pairformer block where the single stream changes. Attention over tokens, with `b_ij` from the pair map added before the softmax — the same mechanism used at atom level in the input embedder, now at token level and 384 channels wide.',
      'Information flows one way here: the pair map informs the single stream, not the reverse. The single stream\'s influence on the pair map comes earlier, through the MSA module and the input embedding.',
      'This block also carries a value residual — the attention values from the first block are mixed into every later block, which keeps a path back to the un-refined representation across all 48 layers.',
    ],
    math: [{ tex: 's_i \\mathrel{+}= \\sum_j \\mathrm{softmax}_j\\!\\left(\\frac{q_i^{\\top} k_j}{\\sqrt{d}} + W_b\\,\\mathrm{LN}(z_{ij})\\right) v_j' }],
    inputs: [
      { name: 'single_repr', symbolic: 'b n ds', concrete: [1, 199, 384] },
      { name: 'pairwise_repr', symbolic: 'b n n dp', concrete: [1, 199, 199, 128] },
    ],
    outputs: [{ name: 'single_repr', symbolic: 'b n ds', concrete: [1, 199, 384] }],
  },
  {
    id: 'single_transition',
    stage: 'trunk',
    title: 'Single transition',
    module: 'Transition',
    algorithm: 'Algorithm 11',
    sourceSymbol: 'Transition.forward',
    traceId: 'single_transition',
    summary: '384 → 1536 → 384, per token. The last sub-layer of the block.',
    detail: [
      'Closes the block. After this the loop returns to triangle multiplication with an updated pair map and an updated single stream, 47 more times.',
    ],
    inputs: [{ name: 'x', symbolic: 'b n ds', concrete: [1, 199, 384] }],
    outputs: [{ name: 'out', symbolic: 'b n ds', concrete: [1, 199, 384] }],
  },
  {
    id: 'pairformer_stack',
    stage: 'trunk',
    title: 'The trunk, finished',
    module: 'PairformerStack',
    algorithm: 'Algorithm 17',
    sourceSymbol: 'PairformerStack.forward',
    traceId: 'pairformer_stack',
    repeats: '48 blocks complete',
    summary: 'The single and pairwise representations that the rest of the network is conditioned on.',
    detail: [
      'Everything downstream — the denoiser, the confidence head, the distogram — reads these two tensors and nothing else from the trunk.',
      'The recorded statistics are worth reading carefully, because they show something real about an untrained network. The single stream leaves the stack at about ±5. The pairwise stream leaves it at ±2 × 10¹⁵.',
      'Forty-eight residual blocks with no trained weights compound: each block adds a branch whose scale is set by random initialisation, and nothing has yet learned to keep the sum bounded. Training is what pulls that back down. It is a genuine measurement of this network in this state, and a good reminder of what the "untrained" caveat on this page actually means.',
    ],
    inputs: [
      { name: 'single_repr', symbolic: 'b n ds', concrete: [1, 199, 384] },
      { name: 'pairwise_repr', symbolic: 'b n n dp', concrete: [1, 199, 199, 128] },
    ],
    outputs: [
      { name: 'single', symbolic: 'b n ds', concrete: [1, 199, 384] },
      { name: 'pairwise', symbolic: 'b n n dp', concrete: [1, 199, 199, 128] },
    ],
  },
]
